Add transaction book
AY2324S1-CS2103T-W13-3/tp pull request #61
Opened 2023-10-14 10:34 UTC by Bombbird2001

A lot of stuff changed, main differences:
- Refactor UniquePersonList, UniqueTransactionList to UniqueEntryList
- Person and Transaction implements the Entry interface which provides isSameEntry method (same as the old isSamePerson method in Person class)
- Rename exceptions that used "Person" in their names to use "Entry" instead
- Rename TransactionLog to TransactionBook, more or less the same as AddressBook class but for transactions; other classes with TransactionLog in their names also changed to use TransactionBook
- Integrate loading of transaction CSV (at app start), saving of transaction (on command execution)
- Update TransactionTablePanel to display the new Transaction properties
- Add TransactionBook related tests

Things still needed:
- More tests for Transaction class
- Transaction class still needs a Date
- Transaction parsing class should parse for the new fields (currently using placeholder)

Resolves #54

2023-10-14 11:30 UTC, cxo05 requested changes

2023-10-14 11:30 UTC, cxo05 commented on src/main/java/transact/logic/commands/AddTransactionCommand.java
>      }
```suggestion
        return new CommandResult(String.format(MESSAGE_SUCCESS, Messages.format(toAdd)), TabWindow.TRANSACTIONS);
```

2023-10-14 11:30 UTC, cxo05 commented on src/main/java/transact/logic/commands/AddTransactionCommand.java
```suggestion
import transact.ui.MainWindow.TabWindow;
```

2023-10-14 11:33 UTC, cxo05 commented on src/main/java/transact/logic/commands/AddTransactionCommand.java
>      }
```suggestion
        return new CommandResult(String.format(MESSAGE_SUCCESS, Messages.format(toAdd)), TabWindow.TRANSACTIONS);
```

2023-10-14 12:06 UTC, Bombbird2001 commented on src/main/java/transact/logic/commands/AddTransactionCommand.java
Updated

2023-10-14 12:06 UTC, Bombbird2001 commented on src/main/java/transact/logic/commands/AddTransactionCommand.java
>      }
Updated

2023-10-14 12:13 UTC, cxo05 commented
Ok LGTM

2023-10-14 12:15 UTC, cxo05 commented
@AlainS87 @PetrichorPrecipice Can take a look too and give comment

2023-10-14 15:08 UTC, cxo05 approved these changes

2023-10-15 04:33 UTC, AlainS87 commented
Looks good

2023-10-15 11:47 UTC, PetrichorPrecipice commented
LGTM

2023-10-15 12:26 UTC, merged